version: '3'

services:

  app:
    build: ./
    image: typescript-docker
    restart: always
    volumes: &appvolumes
      - ./:/app:delegated
    ports:
      - '3000:8080'
    environment: &appenv
      PORT: 8080

  app_watcher:
    build: ./
    image: typescript-docker
    depends_on:
      - app
    restart: always
    volumes: *appvolumes
    environment: *appenv
    command: ["pm2-runtime", "start", "ecosystem.config.js", "--only=app-watcher"]
